DATASET:
  NAME: "DescribableTextures"
  ATTR: [['banded which has varying shades of one color',
  'banded which has a broad range of widths and colors',
  'banded which can be found in nature, or created from fabrics'],
 ['blotchy which has an irregular pattern of spots',
  'blotchy which the spots merge in different directions',
  'blotchy which has an uneven, fuzzy, or mottled appearance'],
 ['braided which consists of three or more strands intertwined together',
  'braided which creates a sturdy, solid material',
  'braided which appears to have an interlocked, rope-like spiral pattern'],
 ['bubbly which appears raised and bumpy',
  'bubbly which can be thick or thin',
  'bubbly which can have a glossy, wet texture'],
 ['bumpy which is rough and uneven',
  'bumpy which can be consistent or irregular',
  'bumpy which can be spiky or rounded'],
 ['chequered which consists of equal sized boxes',
  'chequered which each box has two alternating colors',
  'chequered which may be used in clothing, architecture, or art'],
 ['cobwebbed which can be seen around corners, doorways, furniture, or windows',
  'cobwebbed which looks like a delicate web',
  'cobwebbed which made from silk threads spun together '],
 ['cracked which shows layers of lines and patterns',
  'cracked which is often dry and brittle',
  'cracked which has jagged edges and crevices'],
 ['crosshatched which is composed of two sets of parallel lines that cross each other',
  'crosshatched which the pattern often appears in fabrics or artwork ',
  'crosshatched which is characterized by its interlocking lines'],
 ['crystalline which reflects light in a unique way',
  'crystalline which is often found in nature',
  'crystalline which has a glossy or dull appearance'],
 ['dotted which dots are usually created in a regular pattern',
  'dotted which usually created with paint, fabric, paper, etc.',
  'dotted which dots may be all of the same color or different colors'],
 ['fibrous which can be used in various craft and textile projects',
  'fibrous which has a fibrous web-like appearance',
  'fibrous which looks like a mat or felt fabric'],
 ['flecked which has small, irregular flecks of color ',
  'flecked which is often seen in mottled fabrics',
  'flecked which appears to be speckled and spotted'],
 ['freckled which may be clustered in one area or spread out',
  'freckled which appear on the skin or any surface',
  'freckled which can be found in different colors'],
 ['frilly which appears with a lot of small, intricate folds',
  'frilly which has multiple layers that interconnect',
  'frilly which is generally seen in white or pastel colors'],
 ['gauzy which is soft and delicate',
  'gauzy which is often plain white, but can be dyed in different colors',
  'gauzy which is see-through yet slightly opaque'],
 ['grid which is made of repeating squares',
  'grid which have straight lines, in two directions',
  'grid which can be used in wallpaper or for scrapbooking'],
 ['grooved which is a type of surface texture',
  'grooved which looks like a series of evenly spaced vertical or horizontal ridges',
  'grooved which may appear as a single groove or a pattern of grooves'],
 ['honeycombed which has a hexagon pattern',
  'honeycombed which appears as high and low spots',
  'honeycombed which contains various sizes of hexagons'],
 ['interlaced which has regular, consistent patterns',
  'interlaced which consist of weave-type patterns',
  'interlaced which form pattern with a diamond shape in the center'],
 ['knitted which appears usually in one color',
  'knitted which is looped in a series of connected rows',
  'knitted which can have a seed or moss stitch pattern'],
 ['lacelike which has intricate patterns',
  'lacelike which display an overall lacy effect',
  'lacelike which is often white, cream, or pastel colors'],
 ['lined which is a repeating pattern of thin lines',
  'lined which appears on a surface',
  'lined which can be uniform in size or have different thicknesses'],
 ['marbled which has a mottled, blended, or streaked effect',
  'marbled which has a contrast in shades or hues',
  'marbled which can have a variety of textures depending on the material'],
 ['matted which is a rough, uneven surface',
  'matted which looks knotted with lumps and ridges',
  'matted which appears flattened in a horizontal direction'],
 ['meshed which has multiple criss-crossing lines',
  'meshed which has diamond-shaped openings',
  'meshed which has an open weave'],
 ['paisley which is also seen in wallpaper and home décor',
  'paisley which contains curved and pointed shapes',
  'paisley which is popular on clothing, bags, and accessories'],
 ['perforated which can be used to break up light or noise',
  'perforated which consists of a series of small holes',
  'perforated which can have a uniform or random pattern'],
 ['pitted which has small indentations',
  'pitted which may have ridges',
  'pitted which can be found on natural stones'],
 ['pleated which appears in a shallow or deep fold',
  'pleated which can be pressed in a variety of patterns',
  'pleated which is often used for a decorative effect'],
 ['polka-dotted which can be printed on fabric or paper',
  'polka-dotted which displays two or more colors',
  'polka-dotted which arranged in an orderly pattern'],
 ['porous which has many tiny holes or pores',
  'porous which can absorb liquids quickly',
  'porous which has an uneven and rough surface'],
 ['potholed which consists of shallow craters, pits, and divots',
  'potholed which have a rough, textured surface ',
  'potholed which are usually found on roads'],
 ['scaly which appears as a flat, ridged surface',
  'scaly which is resistant to bending or denting',
  'scaly which has an interlocking pattern'],
 ['smeared which appears to be a mess of forms',
  'smeared which has indistinct boundaries',
  'smeared which has muted colors'],
 ['spiralled which has a curved wave-like shape',
  'spiralled which can be smooth or coarse in texture',
  'spiralled which owns a three-dimensional structure'],
 ['sprinkled which have a rough surface',
  'sprinkled which looks like tiny dots or flecks',
  'sprinkled which usually colored in white, yellow, brown, or other light colors'],
 ['stained which has a blotchy, mottled or speckled appearance',
  'stained which has different shades of the same color',
  'stained which has irregular spots of color'],
 ['stratified which may appear as limestone or sandstone',
  'stratified which appears in horizontal layers',
  'stratified which may contain large fossils'],
 ['striped which contains an alternating pattern of light and dark lines',
  'striped which appear as horizontal, vertical, or diagonal stripes',
  'striped which includes a variety of colors'],
 ['studded which has small, raised bumps',
  'studded which appear rough and bumpy',
  'studded which usually appears on clothing and fabrics'],
 ['swirly which is a repeating, swirling pattern',
  'swirly which is often used in decorative elements',
  'swirly which consists of multiple colors'],
 ['veined which can appear as an abstract or an organic pattern ',
  'veined which has subtle, intricate patterns',
  'veined which has lighter, narrow veins running through the wider lines'],
 ['waffled which has a grid-like pattern',
  'waffled which can be made from different ingredients such as batter, dough, or even chocolate',
  'waffled which is light brown or golden in color'],
 ['woven which appears as a pattern of crisscrossed threads',
  'woven which has a uniform pattern',
  'woven which is commonly used in clothing, upholstery, and other fabrics'],
 ['wrinkled which appears as folded or crumpled',
  'wrinkled which appears as furrowed or corrugated',
  'wrinkled which has a rough or coarse surface'],
 ['zigzagged which appear as a combination of straight and diagonal lines',
  'zigzagged which made up of alternating lines',
  'zigzagged which has an angular appearance']]
  BIAS: [['a background of banded'],
 ['a background of blotchy'],
 ['a background of braided'],
 ['a background of bubbly'],
 ['a background of bumpy'],
 ['a background of chequered'],
 ['a background of cobwebbed'],
 ['a background of cracked'],
 ['a background of crosshatched'],
 ['a background of crystalline'],
 ['a background of dotted'],
 ['a background of fibrous'],
 ['a background of flecked'],
 ['a background of freckled'],
 ['a background of frilly'],
 ['a background of gauzy'],
 ['a background of grid'],
 ['a background of grooved'],
 ['a background of honeycombed'],
 ['a background of interlaced'],
 ['a background of knitted'],
 ['a background of lacelike'],
 ['a background of lined'],
 ['a background of marbled'],
 ['a background of matted'],
 ['a background of meshed'],
 ['a background of paisley'],
 ['a background of perforated'],
 ['a background of pitted'],
 ['a background of pleated'],
 ['a background of polka-dotted'],
 ['a background of porous'],
 ['a background of potholed'],
 ['a background of scaly'],
 ['a background of smeared'],
 ['a background of spiralled'],
 ['a background of sprinkled'],
 ['a background of stained'],
 ['a background of stratified'],
 ['a background of striped'],
 ['a background of studded'],
 ['a background of swirly'],
 ['a background of veined'],
 ['a background of waffled'],
 ['a background of woven'],
 ['a background of wrinkled'],
 ['a background of zigzagged']]