DATASET:
  NAME: "OxfordPets"
  ATTR: [['abyssinian which has vibrant colors of ruddy, red, blue, fawn, silver, and light brown',
  'abyssinian which has a unique tail with a white tip',
  'abyssinian which owns an arch-shaped back'],
 ['american_bulldog which has short and coarse fur',
  'american_bulldog which white, brown, black, brindle, or fawn',
  'american_bulldog which owns a wide chest'],
 ['american_pit_bull_terrier which has a strong, muscular body',
  'american_pit_bull_terrier which has short smooth-coat',
  'american_pit_bull_terrier which has a short, close-lying coat'],
 ['basset_hound which has a deep bark',
  'basset_hound which has a short and stubby tail',
  'basset_hound which has a fine muzzle'],
 ['beagle which has large, droopy ears',
  'beagle which has black, tan and white in color',
  'beagle which has a long and sticky tail'],
 ['bengal which has a short, thick tail',
  'bengal which has a tan, brown or golden coat',
  'bengal which is marked with spots, rosettes, and stripes'],
 ['birman which has four white feet',
  'birman which has a pointed face with a short muzzle',
  'birman which exhibits blue eyes'],
 ['bombay which is a medium-sized, short-haired cat',
  'bombay which owns a glossy black coat',
  'bombay which has short, glossy coat'],
 ['boxer which has a short and glossy coat',
  'boxer which may be brindle, fawn, or white in color',
  'boxer which has deep and pendant-shaped ears'],
 ['british_shorthair which owns a powerful, stocky body',
  'british_shorthair which appears short and thick-set',
  'british_shorthair which has a dense, plush coat'],
 ['chihuahua which has small and round head ',
  'chihuahua which has large and round eyes',
  'chihuahua which has pointed ears'],
 ['egyptian_mau which has a short, mottled coat',
  'egyptian_mau which has a well-defined muzzle',
  'egyptian_mau which is typically gray and spotted with black markings'],
 ['english_cocker_spaniel which has golden to deep chestnut colored fur',
  'english_cocker_spaniel which has a short, straight coat',
  'english_cocker_spaniel which has an alert expression'],
 ['english_setter which has a long, silky coat',
  'english_setter which is white or white-and-tan in colour',
  'english_setter which has long ears'],
 ['german_shorthaired which has a short, dense, glossy coat',
  'german_shorthaired which exhibit a docked or natural bobtail',
  'german_shorthaired which coat colors are brown, black, white, and ticked'],
 ['great_pyrenees which has a thick white double-coated fur',
  'great_pyrenees which has a long, thick, protective double coat',
  'great_pyrenees which has a long and powerful head'],
 ['havanese which exhibits a long tail',
  'havanese which typically has a white, tan, grey, black or cream coat colors',
  'havanese which has a happy expression'],
 ['japanese_chin which has a small-to-medium size',
  'japanese_chin which exhibits a short muzzle',
  'japanese_chin which has wide set, round eyes'],
 ['keeshond which has a thick, grey shaggy coat',
  'keeshond which has a wedge-shaped head',
  'keeshond which has pointed ears that stand erect'],
 ['leonberger which exhibits almond-shaped eyes',
  'leonberger which has a long neck and broad head',
  'leonberger which is black, yellow, and white in color'],
 ['maine_coon which displays large, tufted ears',
  'maine_coon which is brown, grey, and white in color',
  'maine_coon which has a thick, luxurious coat'],
 ['miniature_pinscher which has a high-set, short tail',
  'miniature_pinscher which has erect ears with cropped tips',
  'miniature_pinscher which is black, tan, red, or chocolate color'],
 ['newfoundland which is black, brown, grey, or white',
  'newfoundland which has long wavy hair',
  'newfoundland which ears are medium to large in size and triangular shaped'],
 ['persian which has strong, short legs',
  'persian which possesses a short muzzle',
  'persian which owns a luxurious and glossy coat'],
 ['pomeranian which has a plush double coat',
  'pomeranian which has a fox-like face with small, pointed ears',
  'pomeranian which has a long, fluffy tail'],
 ['pug which has a double-layered coat, with a coarse, straight outercoat and a soft, thick undercoat',
  'pug which has a short muzzle and wrinkled face',
  'pug which has two small, dark eyes'],
 ['ragdoll which has medium-length fur',
  'ragdoll which has blue eyes',
  'ragdoll which have a gentle temperament'],
 ['russian_blue which has large, pointed ears',
  'russian_blue which has a grey/blue-grey colouring',
  'russian_blue which has a green or yellow eyes'],
 ['saint_bernard which has a short muzzle',
  'saint_bernard which head is large and broad',
  'saint_bernard which covered in short-to-medium and dense coat'],
 ['samoyed which has a compact, well-proportioned body',
  'samoyed which has a thick, white double-coat',
  'samoyed which exhibit fox-like muzzle and medium pointed ears'],
 ['scottish_terrier which has small, pricked ears',
  'scottish_terrier which exhibits short legs',
  'scottish_terrier which exhibits a long muzzle and shaggy beard'],
 ['shiba_inu which is a compact spitz breed of Japanese origin',
  'shiba_inu which is square-shaped with well-developed muscles',
  'shiba_inu which has a short, curled tail'],
 ['siamese which may have a dark-colored tail',
  'siamese which coat can come in a variety of colors including seal point, blue point, chocolate point, and lilac point',
  'siamese which has blue eyes'],
 ['sphynx which is a breed of cats',
  'sphynx which has a wrinkled, hairless body',
  'sphynx which has large, almond-shaped eyes'],
 ['staffordshire_bull_terrier which has a broad, square head',
  'staffordshire_bull_terrier which has a powerful, wide-set jaw',
  'staffordshire_bull_terrier which has a strong and muscular neck'],
 ['wheaten_terrier which has a soft, wavy coat',
  'wheaten_terrier which has a strong, square-shaped muzzle',
  'wheaten_terrier which is white, wheaten, or cream colored'],
 ['yorkshire_terrier which small, toy-sized dog ',
  'yorkshire_terrier which appears with black, tan, and blue-gray color',
  'yorkshire_terrier which owns long straight ears']]
  BIAS: [['a background of abyssinian'],
 ['a background of american_bulldog'],
 ['a background of american_pit_bull_terrier'],
 ['a background of basset_hound'],
 ['a background of beagle'],
 ['a background of bengal'],
 ['a background of birman'],
 ['a background of bombay'],
 ['a background of boxer'],
 ['a background of british_shorthair'],
 ['a background of chihuahua'],
 ['a background of egyptian_mau'],
 ['a background of english_cocker_spaniel'],
 ['a background of english_setter'],
 ['a background of german_shorthaired'],
 ['a background of great_pyrenees'],
 ['a background of havanese'],
 ['a background of japanese_chin'],
 ['a background of keeshond'],
 ['a background of leonberger'],
 ['a background of maine_coon'],
 ['a background of miniature_pinscher'],
 ['a background of newfoundland'],
 ['a background of persian'],
 ['a background of pomeranian'],
 ['a background of pug'],
 ['a background of ragdoll'],
 ['a background of russian_blue'],
 ['a background of saint_bernard'],
 ['a background of samoyed'],
 ['a background of scottish_terrier'],
 ['a background of shiba_inu'],
 ['a background of siamese'],
 ['a background of sphynx'],
 ['a background of staffordshire_bull_terrier'],
 ['a background of wheaten_terrier'],
 ['a background of yorkshire_terrier']]